# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98619f609997b386d1c758eb4990d5f86444808bc4f727877616cfba4a30b06b0dce39254c7723828b43991e46891c272a5242739a0257ebfaef97a52d241292

test:
  secret_key_base: e148f8f3ce146263fa54b008fab8371a9d1c5d2fbdda121ba413a3351aa1d900b86f4e87559d6c829711521c936f456f26882575be0bd8232a68a28009f098cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
