 #         10        20        30        40        50
 # 12345678901234567890123456789012345678901234567890
LAND_MAP = [
  "ccccccccccccccccccccccccccccccccccccccccccnnrrrrrr",
  "ccccccccccccccccccccccccccccccccccccccccccnnnrrrrr",
  "cccccccccccccccccccccccccccccccccccccccccnnnnnnrrr",
  "cccccccccccccccccccccccccccccccccccccccnnnnnn.....",
  "cccccccccccccccccccccccccccccccccnnnnnnnnnnn......",
  "ccccccccccccccccccccccccccccccccccnnnnnnnnnn......",
  "ccccccccccccccccccccccccccnnnnnnnnnnnnnnnnnn......",
  "ccccccccccccccccccccccccccnnnnnnnnnnnnnnnnnn......",
  "cccccccccccccccccccccccccnnnnnnnnnnnnnnnnnn.......",
  "ccccccccccccccccccccccnnnnnnnnnnnnnnnnnnn.........",
  "ccccccccccccccccccnnnnnnnnnnnnnnnnnnnnn...........",
  "ccccccccccccccnnnnnnnnnnnnnnnnnnnnnnn.............",
  "cccccccccnnnnnnnnnnnnnnnnnnnnnn...................",
  "..........nnnnnnnnnnnnnnnnnnn.....................",
  "..............nnnnnnnnnnnnnnn.....................",
  "..................nnnnnnnnnnnnnnn.................",
  "..................nnnnnnnnnnnnnnnn................",
  ".................nnnnnnnnnnnnnnnnnn...............",
  "..............nnnnnnnnnnnnnnnnnnnn................",
  "............nnnnnnnnnnnnnnnnnnnnnnnn..............",
  "............nnnnnnnnnnnnnnnnnnnnnnnn..............",
  "...............nnnnnnnnssssssnnnnnnnnn............",
  "................ssssssssssssssssssssss............",
  "...............ssssssssssssssssssssssss...........",
  ".............sssssssssssssssssssssssssss..........",
  "..............sssssssssssssssssssssssssss.........",
  "................ssssssssssssssssssssssss..........",
  "................sssssssssssssssssssssss...........",
  "................sssssssssssssssssssssss...........",
  "...............sssssssssssssssssssssss............",
  "...............sssssssssssssssssssssssss..........",
  "...............ssssssssssssssssssssssss...........",
  "...............sssssssssssssssssssssss............",
  "................sssssssssssssssssssss.............",
  "................s...sss...ss......s...............",
  "..................................................",
  "..................................................",
  "................ssss..............................",
  "..............ssssss..............................",
  "..................................................",
  "..................................................",
  "..................................................",
  "..................................................",
  "..................................................",
  "..................................................",
  "..................................................",
  "..................................................",
  "..................................................",
  "..................................................",
  ".................................................."
]

 #         10        20        30        40        50
 # 12345678901234567890123456789012345678901234567890
